version: 2.1

jobs:
  build:
    parallelism: 20
    docker:
      - image: cimg/base:stable
    steps:
      # - run: git config --global feature.experimental blobless
      # - checkout
      - run: git clone --filter=blob:limit=1m https://github.com/ogii-test/linux.git
